IF EXISTS(SELECT * FROM sys.databases WHERE name = 'stage')
BEGIN
    ALTER DATABASE stage SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE stage;
END
GO

CREATE DATABASE stage;
GO

IF EXISTS(SELECT * FROM sys.databases WHERE name = 'main')
BEGIN
    ALTER DATABASE main SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE main;
END
GO

CREATE DATABASE main;
GO
